import { subtitleLanguageCode } from "../../../src/catalogue/contract";
import { adpSourceLine } from "./adp";
import type { AdpPageLine, SubtitleLine } from "./ledger";
import { OPENSUBTITLES_SOURCE } from "./opensubtitles";

/**
 * Turns the ledgers into one SQL file of upserts for public.catalogue_title_accessibility.
 * The backfill never holds a write credential: the app has no service-role key by design, and
 * the table is read-only through the API. Sergio applies the file as the database owner.
 *
 * Every value is either a validated integer, a validated language code, an ISO timestamp from
 * `Date`, or a fixed/provider string escaped as a SQL literal, so no ledger text is ever
 * spliced raw into the statement.
 */

const CHUNK = 500;

export type CatalogueRef = { titleId: number; imdbId: string };
type CheckedLine = Extract<SubtitleLine, { outcome: "checked" }>;

export function sqlLiteral(value: string) {
  return `'${value.replace(/'/g, "''")}'`;
}

function timestamp(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) throw new Error(`not a timestamp: ${value}`);
  return `${sqlLiteral(date.toISOString())}::timestamptz`;
}

function languagesArray(languages: string[]) {
  for (const code of languages) {
    if (!subtitleLanguageCode.safeParse(code).success) throw new Error(`not a language code: ${code}`);
  }
  return `array[${languages.map(sqlLiteral).join(",")}]::text[]`;
}

function titleId(value: number) {
  if (!Number.isSafeInteger(value) || value <= 0) throw new Error(`not a title id: ${value}`);
  return String(value);
}

function chunks<T>(items: T[]) {
  const out: T[][] = [];
  for (let index = 0; index < items.length; index += CHUNK) out.push(items.slice(index, index + CHUNK));
  return out;
}

export function subtitleUpserts(answers: CheckedLine[]) {
  return chunks(answers).map(
    (chunk) =>
      `insert into public.catalogue_title_accessibility (title_id, subtitle_languages, subtitle_count, subtitle_checked_at, subtitle_source) values\n` +
      chunk
        .map(
          (line) =>
            `  (${titleId(line.titleId)}, ${languagesArray(line.languages)}, ${Math.trunc(line.count)}, ${timestamp(line.checkedAt)}, ${sqlLiteral(OPENSUBTITLES_SOURCE)})`,
        )
        .join(",\n") +
      `\non conflict (title_id) do update set subtitle_languages = excluded.subtitle_languages, subtitle_count = excluded.subtitle_count,` +
      ` subtitle_checked_at = excluded.subtitle_checked_at, subtitle_source = excluded.subtitle_source;`,
  );
}

export type AudioDescriptionYes = { titleId: number; source: string; checkedAt: string };

/**
 * Only catalogue films the directory lists become rows, each a sourced yes. Films it does not
 * list are left untouched: unknown, never false.
 */
export function audioDescriptionYeses(pages: AdpPageLine[], catalogue: CatalogueRef[]): AudioDescriptionYes[] {
  const listed = new Map<string, { providers: Set<string>; checkedAt: string }>();
  for (const page of pages) {
    for (const entry of page.entries) {
      const known = listed.get(entry.imdbId) ?? { providers: new Set<string>(), checkedAt: page.fetchedAt };
      entry.providers.forEach((provider) => known.providers.add(provider));
      if (page.fetchedAt > known.checkedAt) known.checkedAt = page.fetchedAt;
      listed.set(entry.imdbId, known);
    }
  }
  return catalogue.flatMap(({ titleId: id, imdbId }) => {
    const hit = listed.get(imdbId);
    return hit ? [{ titleId: id, source: adpSourceLine([...hit.providers].sort()), checkedAt: hit.checkedAt }] : [];
  });
}

export function audioDescriptionUpserts(yeses: AudioDescriptionYes[]) {
  return chunks(yeses).map(
    (chunk) =>
      `insert into public.catalogue_title_accessibility (title_id, has_audio_description, audio_description_source, audio_description_checked_at) values\n` +
      chunk
        .map((yes) => `  (${titleId(yes.titleId)}, true, ${sqlLiteral(yes.source)}, ${timestamp(yes.checkedAt)})`)
        .join(",\n") +
      `\non conflict (title_id) do update set has_audio_description = excluded.has_audio_description,` +
      ` audio_description_source = excluded.audio_description_source, audio_description_checked_at = excluded.audio_description_checked_at;`,
  );
}

export function sqlFile(statements: string[], header: string) {
  return [`-- ${header}`, "-- Generated by apps/backfill/accessibility.ts. Apply as the database owner.", "begin;", ...statements, "commit;", ""].join("\n");
}
