import { z } from "zod";

// Script timing is configurable per jam: the host picks the total runtime and
// the portion length band. Soft bounds are what we ask the writer for; hard
// bounds add a little slack so a beat can breathe without breaking validation.
export const DEFAULT_TOTAL_SECONDS = 20;
export const DEFAULT_PORTION_MIN_SECONDS = 5;
export const DEFAULT_PORTION_MAX_SECONDS = 5;

// 10s floor keeps tiny test jams possible (e.g. a 10-second jam of 5-second
// portions) while still requiring at least two portions of the shortest kind.
export const TOTAL_MIN_SECONDS = 10;
// The absolute band is the video model's band, not a product preference:
// MiniMax H3 Max accepts a whole-second duration in [5, 15], and the Director
// realtime model publishes the same numbers as min/max chunk duration. A
// portion outside this band cannot be generated by anything this build can
// call, so it is refused at the script boundary rather than at generation time.
// See apps/server/providers/falModels.ts and docs/DECISIONS.md.
export const PORTION_ABSOLUTE_MIN_SECONDS = 5;
export const PORTION_ABSOLUTE_MAX_SECONDS = 15;
export const PORTION_SLACK_SECONDS = 2;
// Bounds scriptwriter output: a format may never require more portions than this.
export const MAX_PORTIONS = 48;
// The longest jam that can actually be rendered: every portion must fit the
// model band, and there may be at most MAX_PORTIONS of them. Stating it as a
// derived value stops the ceiling from drifting away from what is reachable.
export const TOTAL_MAX_SECONDS = MAX_PORTIONS * PORTION_ABSOLUTE_MAX_SECONDS;

// A beat is the one-phrase summary of a portion. The outline is the ordered list
// of beats and is the surface participants read and edit instead of the
// screenplay, so a beat must stay glanceable: one phrase, not a paragraph.
// Optional on the schema because revisions written before the outline existed
// carry no beats, and history is append-only — they can never gain one.
export const BEAT_MAX_CHARS = 120;

export const scriptFormatSchema = z
  .object({
    totalSeconds: z
      .number()
      .int()
      .min(TOTAL_MIN_SECONDS)
      .max(TOTAL_MAX_SECONDS)
      .default(DEFAULT_TOTAL_SECONDS),
    portionMinSeconds: z
      .number()
      .int()
      .min(PORTION_ABSOLUTE_MIN_SECONDS)
      .max(PORTION_ABSOLUTE_MAX_SECONDS)
      .default(DEFAULT_PORTION_MIN_SECONDS),
    portionMaxSeconds: z
      .number()
      .int()
      .min(PORTION_ABSOLUTE_MIN_SECONDS)
      .max(PORTION_ABSOLUTE_MAX_SECONDS)
      .default(DEFAULT_PORTION_MAX_SECONDS),
  })
  .superRefine((format, context) => {
    if (format.portionMinSeconds > format.portionMaxSeconds) {
      context.addIssue({
        code: "custom",
        path: ["portionMinSeconds"],
        message: "The minimum portion length cannot exceed the maximum.",
      });
    }
    if (format.portionMaxSeconds > format.totalSeconds) {
      context.addIssue({
        code: "custom",
        path: ["portionMaxSeconds"],
        message: "A single portion cannot be longer than the whole script.",
      });
    }
    if (format.totalSeconds / format.portionMinSeconds > MAX_PORTIONS) {
      context.addIssue({
        code: "custom",
        path: ["portionMinSeconds"],
        message: `This format could need more than ${MAX_PORTIONS} portions; raise the minimum portion length or shorten the script.`,
      });
    }
  });

export type ScriptFormat = z.infer<typeof scriptFormatSchema>;

export const DEFAULT_SCRIPT_FORMAT: ScriptFormat = scriptFormatSchema.parse({});

export function hardPortionBounds(format: ScriptFormat): {
  min: number;
  max: number;
} {
  // Slack lets a beat breathe, but never outside the band the video model
  // accepts: widening past it would let the writer produce a portion that is
  // then impossible to render.
  return {
    min: Math.max(
      PORTION_ABSOLUTE_MIN_SECONDS,
      format.portionMinSeconds - PORTION_SLACK_SECONDS,
    ),
    max: Math.min(
      PORTION_ABSOLUTE_MAX_SECONDS,
      format.portionMaxSeconds + PORTION_SLACK_SECONDS,
    ),
  };
}

// ~6% of the runtime; the 2s floor dominates at the short default, which is
// what keeps a 20-second jam from drifting into a fifth portion.
export function totalToleranceSeconds(format: ScriptFormat): number {
  return Math.max(2, Math.round(format.totalSeconds / 16));
}

function buildPortionSchema(minSeconds: number, maxSeconds: number) {
  return z.object({
    durationSeconds: z.number().int().min(minSeconds).max(maxSeconds),
    summary: z.string().trim().min(1).max(BEAT_MAX_CHARS).optional(),
    action: z.string().trim().min(1).max(600),
    dialogue: z.string().trim().max(600).optional(),
    visualDirection: z.string().trim().max(400).optional(),
  });
}

function buildSceneSchema(minSeconds: number, maxSeconds: number) {
  return z.object({
    heading: z.string().trim().min(1).max(160),
    portions: z.array(buildPortionSchema(minSeconds, maxSeconds)).min(1).max(48),
  });
}

/** Strict script schema for a given format: hard portion bounds + total tolerance. */
export function createJamScriptSchema(format: ScriptFormat) {
  const bounds = hardPortionBounds(format);
  const tolerance = totalToleranceSeconds(format);
  return z
    .object({
      title: z.string().trim().min(1).max(120),
      logline: z.string().trim().min(1).max(400),
      scenes: z.array(buildSceneSchema(bounds.min, bounds.max)).min(1).max(24),
    })
    .superRefine((script, context) => {
      const total = totalDurationSeconds(script);
      if (Math.abs(total - format.totalSeconds) > tolerance) {
        context.addIssue({
          code: "custom",
          path: ["scenes"],
          message: `Script runs ${total}s; it must stay within ${tolerance}s of ${format.totalSeconds}s.`,
        });
      }
    });
}

// Structural schema for stored/transported scripts: format-agnostic, so a jam
// with a custom format still validates. Strict timing checks happen at
// generation time through createJamScriptSchema(jam.format).
export const jamScriptSchema = z.object({
  title: z.string().trim().min(1).max(120),
  logline: z.string().trim().min(1).max(400),
  scenes: z
    .array(
      buildSceneSchema(
        PORTION_ABSOLUTE_MIN_SECONDS,
        PORTION_ABSOLUTE_MAX_SECONDS,
      ),
    )
    .min(1)
    .max(24),
});

export type ScenePortion = z.infer<typeof jamScriptSchema>["scenes"][number]["portions"][number];
export type Scene = z.infer<typeof jamScriptSchema>["scenes"][number];
export type JamScript = z.infer<typeof jamScriptSchema>;

export function totalDurationSeconds(script: {
  scenes: { portions: { durationSeconds: number }[] }[];
}): number {
  return script.scenes.reduce(
    (sceneSum, scene) =>
      sceneSum +
      scene.portions.reduce((sum, portion) => sum + portion.durationSeconds, 0),
    0,
  );
}
